import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { User, Role } from './types';
// Sprint A2 — build-time generated client pack (single source of truth shared
// with public/role-gate-pack.js). Generated by scripts/gen-role-pack.mjs from
// the active vertical's YAML. Type-only `SolutionPackClient` import inside the
// generated file keeps this dependency value-only here (no runtime cycle).
import { GENERATED_CLIENT_PACK } from './solution-pack.generated';

interface AuthState {
  token: string | null;
  user: User | null;
  setSession: (token: string, user: User) => void;
  clear: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      token: null,
      user: null,
      setSession: (token, user) => set({ token, user }),
      clear: () => set({ token: null, user: null }),
    }),
    {
      name: 'rwr.auth',
      storage: {
        getItem: (name) => {
          const raw = localStorage.getItem(name);
          return raw ? JSON.parse(raw) : null;
        },
        setItem: (name, value) => localStorage.setItem(name, JSON.stringify(value)),
        removeItem: (name) => localStorage.removeItem(name),
      },
    },
  ),
);

// ---- Role helpers ---------------------------------------------------------
// platform:admin is treated as super-user and satisfies any role check.
export function hasRole(role: Role | string): boolean {
  const roles = useAuthStore.getState().user?.roles ?? [];
  return roles.includes('platform:admin') || roles.includes(role);
}

export function hasAnyRole(...roles: Array<Role | string>): boolean {
  return roles.some(hasRole);
}

export function useHasRole(role: Role | string): boolean {
  const user = useAuthStore((s) => s.user);
  const roles = user?.roles ?? [];
  return roles.includes('platform:admin') || roles.includes(role);
}

export function useHasAnyRole(...roles: Array<Role | string>): boolean {
  const user = useAuthStore((s) => s.user);
  const userRoles = user?.roles ?? [];
  if (userRoles.includes('platform:admin')) return true;
  return roles.some((r) => userRoles.includes(r));
}

// ---- SolutionPack (Sprint A1) ---------------------------------------------
// The role→surface mappings below are now DATA-DRIVEN by the active vertical's
// SolutionPack (`packages/config/verticals/<id>.yaml`). The frontend is a
// browser bundle and cannot read YAML/node:fs at runtime, so the RWR reference
// pack's mappings are embedded here as the default client pack — they reproduce
// the previously-hardcoded S12 logic BYTE-FOR-BYTE. A different vertical can
// override `activeClientPack` (e.g. at build time from its YAML) without
// touching this code. The hardcoded if-ladder is retained as the fallback when
// no pack resolves (defensive, behaviour-preserving).
//
// Sprint 9.1 — split operations from field work:
//   * ops.field_specialist  (INTERNAL ops boot to field.html)
//   * ops.coordinator       (dispatcher; boots to operations.html)
//   * field.technician      (EXTERNAL vendor/contractor — field.html)
// =============================================================================
/** A pack-declared branded basemap (id/name/use). The dashboard engine owns
 *  the tile/filter rendering; the pack governs which basemaps appear + order. */
export interface SolutionPackBasemap {
  id: string;
  name?: string;
  use?: string;
}

/** A pack-declared default saved scene (crm.project_scene shape, camelCased). */
export interface SolutionPackSeedScene {
  title: string;
  description?: string | null;
  isDefault?: boolean;
  ordinal?: number;
  centerLat: number;
  centerLon: number;
  zoom?: number;
  pitch?: number;
  bearing?: number;
  basemapId: string;
  sarOverlay?: boolean;
  sarOpacity?: number;
  activeLayers?: ReadonlyArray<string>;
}

export interface SolutionPackClient {
  id: string;
  /** Ordered role → primary surface. First matching key wins. The literal
   *  'vendor:*' matches any vendor:* role; '*admin' === platform:admin. */
  primarySurfaceByRole: ReadonlyArray<readonly [string, string]>;
  /** Role → allowed surfaces. '*admin' sees ALL_AUTHED_SURFACES; 'vendor:*'
   *  matches any vendor:* role. Order is significant for first-match-wins. */
  roleSurfaceAllowList: ReadonlyArray<readonly [string, ReadonlyArray<string>]>;
  // ---- Sprint A3 levers (optional so the in-file RWR fallback need not list
  // them; the build-time generated pack always populates them). --------------
  /** Flat noun/KPI label map (entities ∪ kpis). Read via vocab.ts `t()`. */
  vocabulary?: Readonly<Record<string, string>>;
  /** Branded basemaps this vertical surfaces, in picker order. */
  basemaps?: ReadonlyArray<SolutionPackBasemap>;
  /** id of the default basemap (appears in basemaps[]). */
  defaultBasemap?: string;
  /** Default saved scenes seeded per vertical. */
  seedScenes?: ReadonlyArray<SolutionPackSeedScene>;
}

// RWR reference pack — mirrors packages/config/verticals/rwr.yaml exactly.
const RWR_CLIENT_PACK: SolutionPackClient = {
  id: 'rwr',
  primarySurfaceByRole: [
    ['platform:admin', 'tenants.html'],
    ['vendor:*', 'vendor.html'],
    ['ops.field_specialist', 'field.html'],
    ['field.technician', 'field.html'],
    ['field:technician', 'field.html'],
    ['ops.coordinator', 'operations.html'],
    ['ops:manage', 'operations.html'],
    ['sales:manage', 'sales.html'],
    ['analytics:view', 'analytics.html'],
    ['customer:view', 'customer.html'],
    ['dashboard:view', 'dashboard.html'],
  ],
  roleSurfaceAllowList: [
    ['vendor:*', ['vendor.html']],
    ['field.technician', ['field.html']],
    ['field:technician', ['field.html']],
    ['ops.field_specialist', ['field.html']],
    ['ops.coordinator', ['operations.html', 'dashboard.html', 'pm.html', 'analytics.html']],
    ['ops:manage', ['operations.html', 'dashboard.html', 'pm.html', 'analytics.html']],
    ['sales:manage', ['sales.html', 'analytics.html']],
    ['analytics:view', ['analytics.html']],
    ['customer:view', ['customer.html']],
  ],
};

// The active client pack. Sprint A2: sourced from the build-time GENERATED
// pack (`solution-pack.generated.ts`) — the SINGLE SOURCE OF TRUTH shared with
// public/role-gate-pack.js, derived from the active vertical's YAML by
// scripts/gen-role-pack.mjs. RWR_CLIENT_PACK remains the defensive fallback if
// the generated import is somehow absent/invalid (never leave routing ungated).
function resolveInitialClientPack(): SolutionPackClient {
  try {
    if (
      GENERATED_CLIENT_PACK &&
      Array.isArray(GENERATED_CLIENT_PACK.primarySurfaceByRole) &&
      Array.isArray(GENERATED_CLIENT_PACK.roleSurfaceAllowList) &&
      GENERATED_CLIENT_PACK.primarySurfaceByRole.length > 0
    ) {
      return GENERATED_CLIENT_PACK;
    }
  } catch {
    /* fall through to RWR fallback */
  }
  return RWR_CLIENT_PACK;
}

let activeClientPack: SolutionPackClient = resolveInitialClientPack();

export function setActiveClientPack(pack: SolutionPackClient): void {
  activeClientPack = pack;
}
export function getActiveClientPack(): SolutionPackClient {
  return activeClientPack;
}

function roleMatches(key: string, roles: ReadonlyArray<string>): boolean {
  if (key === '*admin') return roles.includes('platform:admin');
  if (key === 'vendor:*') return roles.some((r) => r.startsWith('vendor:'));
  return roles.includes(key);
}

export function primarySurfaceForRoles(roles: ReadonlyArray<string>): string {
  const pack = activeClientPack ?? RWR_CLIENT_PACK;
  // platform:admin always wins (super-user) regardless of pack ordering.
  if (roles.includes('platform:admin')) {
    const adminEntry = pack.primarySurfaceByRole.find(([k]) => k === 'platform:admin' || k === '*admin');
    if (adminEntry) return adminEntry[1];
    return 'tenants.html';
  }
  for (const [key, surface] of pack.primarySurfaceByRole) {
    if (key === 'platform:admin' || key === '*admin') continue;
    if (roleMatches(key, roles)) return surface;
  }
  return 'login.html';
}

// ---- Role → allowed-surfaces allow-list (Sprint 12) -----------------------
// Single source of truth for which HTML entrypoints a role bundle is
// permitted to visit. Used by:
//   * Login.tsx — to sanitize the `?next=` param so a user with the wrong
//     role can't be deep-linked to a forbidden surface.
//   * TopNav.tsx — to hide cross-surface links the user can't visit.
//   * The inline `role-gate.js` script embedded in every authenticated HTML
//     entry — defense-in-depth UX (NOT authorization; real authz lives in
//     `requirePermission` middleware on the server).
//
// CRITICAL: this is a CLIENT-side UX gate. The server-side
// `requirePermission` middleware on every /api/v1 route is the actual
// security boundary. This function just prevents users from seeing
// surfaces they can't usefully interact with.
// =============================================================================
const ALL_AUTHED_SURFACES: ReadonlySet<string> = new Set([
  'tenants.html', 'staff.html', 'sales.html', 'pm.html', 'analytics.html',
  'operations.html', 'customer.html', 'vendor.html', 'field.html',
  'dashboard.html', 'login.html',
]);

export function allowedSurfacesForRoles(roles: ReadonlyArray<string>): Set<string> {
  // platform:admin sees EVERY surface (super-user).
  if (roles.includes('platform:admin')) return new Set(ALL_AUTHED_SURFACES);

  // login.html is always permitted (the bounce-back surface).
  const allowed = new Set<string>(['login.html']);

  // Pack-driven first-match: the RWR pack's roleSurfaceAllowList reproduces the
  // exact S12 ordering. The first matching clause wins and short-circuits — a
  // user with only dashboard:view matches NOTHING and stays on login.html (the
  // intentional S12 legacy demotion is preserved by simply omitting it).
  const pack = activeClientPack ?? RWR_CLIENT_PACK;
  for (const [key, surfaces] of pack.roleSurfaceAllowList) {
    if (key === '*admin') continue; // handled above
    if (roleMatches(key, roles)) {
      for (const s of surfaces) allowed.add(s);
      return allowed;
    }
  }
  return allowed;
}

export function canVisit(surface: string, roles: ReadonlyArray<string>): boolean {
  return allowedSurfacesForRoles(roles).has(surface);
}

// Sanitize a `?next=` path against open-redirect, traversal, and foreign-host
// attacks. Returns the bare surface filename ('dashboard.html') if it's safe,
// or null otherwise. The caller is responsible for checking the surface is in
// the user's allow-list.
//
// Acceptable inputs:
//   '/dashboard.html'         → 'dashboard.html'
//   'dashboard.html'          → 'dashboard.html'
//   '/field.html?tab=jobs'    → 'field.html'   (query stripped)
// Rejected:
//   'https://evil.com/x.html' → null  (foreign host)
//   '//evil.com/x.html'       → null  (protocol-relative)
//   '/../etc/passwd'          → null  (traversal)
//   '/foo'                    → null  (not .html)
export function sanitizeNextUrl(next: string | null | undefined): string | null {
  if (!next || typeof next !== 'string') return null;
  // Reject anything that looks like a foreign URL or protocol-relative path.
  if (/^[a-z]+:/i.test(next))     return null;
  if (next.startsWith('//'))      return null;
  // Strip leading slash and any query/hash.
  let path = next.replace(/^\/+/, '');
  const qIdx = path.search(/[?#]/);
  if (qIdx >= 0) path = path.slice(0, qIdx);
  // Reject traversal.
  if (path.includes('..') || path.includes('\\')) return null;
  // Must be a simple filename ending in .html, no slashes.
  if (path.includes('/'))         return null;
  if (!/\.html$/.test(path))      return null;
  return path;
}
