// AUTO-GENERATED by mvp/scripts/gen-role-pack.mjs — DO NOT EDIT BY HAND.
// Active vertical: farm (pack id=farm v1.0.0).
// Single source of truth for client routing maps, shared with
// public/role-gate-pack.js. auth-store.ts installs this as the active client
// pack. For the RWR default this equals the S12 maps byte-for-byte.
import type { SolutionPackClient } from './auth-store';

export const GENERATED_CLIENT_PACK: SolutionPackClient = {
  id: "farm",
  primarySurfaceByRole: [
    ["platform:admin", "tenants.html"],
    ["vendor:*", "vendor.html"],
    ["field.technician", "field.html"],
    ["field:technician", "field.html"],
    ["ops:manage", "operations.html"],
    ["sales:manage", "sales.html"],
    ["farm.portfolio.view", "sales.html"],
    ["analytics:view", "analytics.html"],
    ["customer:view", "customer.html"],
    ["farm:view", "customer.html"],
    ["dashboard:view", "dashboard.html"],
  ],
  roleSurfaceAllowList: [
    ["*admin", ["tenants.html", "staff.html", "sales.html", "pm.html", "analytics.html", "operations.html", "customer.html", "vendor.html", "field.html", "dashboard.html", "login.html"]],
    ["vendor:*", ["vendor.html"]],
    ["field.technician", ["field.html"]],
    ["field:technician", ["field.html"]],
    ["ops:manage", ["operations.html", "dashboard.html", "pm.html", "analytics.html"]],
    ["sales:manage", ["sales.html", "analytics.html"]],
    ["farm.portfolio.view", ["sales.html", "analytics.html"]],
    ["analytics:view", ["analytics.html"]],
    ["customer:view", ["customer.html"]],
    ["farm:view", ["customer.html"]],
  ],
  vocabulary: {
    "detection": "observation",
    "detectionPlural": "observations",
    "areaOfInterest": "parcel",
    "pointOfInterest": "zone",
    "asset": "field",
    "farm": "farm",
    "parcel": "parcel",
    "zone": "zone",
    "supplier": "supplier",
    "sourcingRegion": "sourcing region",
    "observation": "observation",
    "alert": "alert",
    "report": "report",
    "detections": "Observations recorded",
    "aoiCount": "Parcels monitored",
    "suppliersTracked": "Suppliers tracked",
    "yieldAtRisk": "Estimated yield at risk",
    "responseTime": "Mean response time"
  },
  basemaps: [
    {
      "id": "satellite",
      "name": "Satellite",
      "use": "True-color imagery — field baseline"
    },
    {
      "id": "greenline",
      "name": "CropVigor",
      "use": "NDVI vegetation index — canopy vigor and biomass; stress and gaps stand out"
    },
    {
      "id": "hydrovision",
      "name": "SoilMoisture",
      "use": "Moisture saturation pseudo-color — irrigation coverage and waterlogging"
    },
    {
      "id": "thermsight",
      "name": "CanopyTherm",
      "use": "Thermal infrared — crop water stress and evapotranspiration hotspots"
    },
    {
      "id": "echoscan",
      "name": "RadarScan",
      "use": "Sentinel-1 SAR backscatter — soil moisture and structure through cloud cover"
    },
    {
      "id": "coherencemap",
      "name": "ChangeMap",
      "use": "InSAR change-detection — tillage, harvest, and field change between passes"
    },
    {
      "id": "deepgrid",
      "name": "ParcelGrid",
      "use": "Minimal-clutter streets — parcel/boundary drawing and route planning"
    },
    {
      "id": "riskatlas",
      "name": "RiskAtlas",
      "use": "Risk heatmap fused over satellite — portfolio/executive briefing view"
    }
  ],
  defaultBasemap: "satellite",
  seedScenes: [
    {
      "title": "Farm Overview",
      "description": "Default parcel view — observations + zones on satellite",
      "isDefault": true,
      "ordinal": 0,
      "centerLat": 36.7468,
      "centerLon": -119.7726,
      "zoom": 12,
      "pitch": 0,
      "bearing": 0,
      "basemapId": "satellite",
      "sarOverlay": false,
      "sarOpacity": 60,
      "activeLayers": [
        "parcels",
        "zones",
        "observations"
      ]
    },
    {
      "title": "Crop vigor",
      "description": "CropVigor basemap — NDVI canopy vigor and stress",
      "isDefault": false,
      "ordinal": 1,
      "centerLat": 36.7468,
      "centerLon": -119.7726,
      "zoom": 15,
      "pitch": 0,
      "bearing": 0,
      "basemapId": "greenline",
      "sarOverlay": false,
      "sarOpacity": 60,
      "activeLayers": [
        "parcels",
        "observations"
      ]
    },
    {
      "title": "Water stress",
      "description": "CanopyTherm — crop water stress and irrigation hotspots",
      "isDefault": false,
      "ordinal": 2,
      "centerLat": 36.7468,
      "centerLon": -119.7726,
      "zoom": 14,
      "pitch": 0,
      "bearing": 0,
      "basemapId": "thermsight",
      "sarOverlay": false,
      "sarOpacity": 60,
      "activeLayers": [
        "parcels",
        "zones",
        "observations"
      ]
    }
  ],
};
