// Single source of truth for brand strings. Hard-code one default; runtime
// override via VITE_PUBLIC_HOST.
//
// This module is consumed by:
//   - Vite-bundled JS / TSX (preferred — import.meta.env is statically replaced)
//   - Static HTML pages via <script type="module"> imports where applicable
//
// To change the public host or from-address for a deployment, set
// VITE_PUBLIC_HOST / VITE_EMAIL_FROM in .env.local — do not edit this file.

/* eslint-disable */

// Vite replaces `import.meta.env.*` at build time. Fall back to safe defaults
// when the constant is missing (e.g., consumed via a non-bundled context).
const _env = (typeof import.meta !== 'undefined' && import.meta && import.meta.env) ? import.meta.env : {};

export const BRAND_NAME       = 'Report.Farm';
export const BRAND_LEGAL_NAME = 'Report.Farm';

export const BRAND_HOST       = _env.VITE_PUBLIC_HOST || 'https://report.farm';

// Derive bare host (no protocol, no trailing slash) for places that need it
// raw — JSON-LD `url`, meta og:url, footers, etc.
export const BRAND_HOST_BARE  = String(BRAND_HOST).replace(/^https?:\/\//i, '').replace(/\/+$/, '');

export const EMAIL_FROM       = _env.VITE_EMAIL_FROM || 'noreply@report.farm';
export const EMAIL_OPS        = 'ops@report.farm';
export const EMAIL_SUPPORT    = 'support@report.farm';
export const EMAIL_RECOVERY   = 'recovery@report.farm';
export const EMAIL_PARTNERS   = 'partners@report.farm';
export const EMAIL_PRESS      = 'press@report.farm';

// Grouped mailto helpers — keeps templates terse.
export const CONTACT = Object.freeze({
  ops:      `mailto:${EMAIL_OPS}`,
  support:  `mailto:${EMAIL_SUPPORT}`,
  recovery: `mailto:${EMAIL_RECOVERY}`,
  partners: `mailto:${EMAIL_PARTNERS}`,
  press:    `mailto:${EMAIL_PRESS}`,
});

export default {
  BRAND_NAME,
  BRAND_LEGAL_NAME,
  BRAND_HOST,
  BRAND_HOST_BARE,
  EMAIL_FROM,
  EMAIL_OPS,
  EMAIL_SUPPORT,
  EMAIL_RECOVERY,
  EMAIL_PARTNERS,
  EMAIL_PRESS,
  CONTACT,
};
